version: '3.5'

services:
  postgresql:
    container_name: postgres-10
    image: postgres:10.15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - blablanet
    restart: unless-stopped
  blablatest-server:
    container_name: blablatest-server
    image: blablatest-server:latest
    ports:
      - "8080:8080"
    networks:
      - blablanet
    depends_on:
      - postgresql
    environment:
      SPRING_R2DBC_URL : r2dbc:postgresql://postgresql:5432/blabladb
      SPRING_flyway_URL : jdbc:postgresql://postgresql:5432/blabladb

networks:
  blablanet:
    driver: bridge
