version: '3.5'

services:
  postgresql:
    container_name: postgres-10
    image: postgres:10.15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - blablanet
    restart: unless-stopped

networks:
  blablanet:
    driver: bridge
